name: "certgen"
version: "1.0"
usage: "Autostart OP modules en K8s"
description: |-
  This plugin escale Onesait Platform pods on k8s deployments

  Usage:

  > helm autostart install onesaitplatform/onesait-platform-chart \
               --namespace onesait-platform \
               --generate-name \
               --version 2

  or simply

  > helm autostart --namespace <namespace_name>
ignoreFlags: false
command: "$HELM_PLUGIN_DIR/autostart.sh"
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/autostart.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/autostart.sh"
